[{"user": {"following_url": "https://api.github.com/users/acatangiu/following{/other_user}", "url": "https://api.github.com/users/acatangiu", "site_admin": false, "gists_url": "https://api.github.com/users/acatangiu/gists{/gist_id}", "node_id": "MDQ6VXNlcjMxOTE3OTcz", "starred_url": "https://api.github.com/users/acatangiu/starred{/owner}{/repo}", "gravatar_id": "", "id": 31917973, "events_url": "https://api.github.com/users/acatangiu/events{/privacy}", "avatar_url": "https://avatars3.githubusercontent.com/u/31917973?v=4", "login": "acatangiu", "repos_url": "https://api.github.com/users/acatangiu/repos", "subscriptions_url": "https://api.github.com/users/acatangiu/subscriptions", "followers_url": "https://api.github.com/users/acatangiu/followers", "html_url": "https://github.com/acatangiu", "received_events_url": "https://api.github.com/users/acatangiu/received_events", "type": "User", "organizations_url": "https://api.github.com/users/acatangiu/orgs"}, "issue_url": "https://api.github.com/repos/rust-vmm/kvm-ioctls/issues/71", "body": "@andreeaflorescu @sameo @jiangliu I've addressed the last issue listed in https://github.com/rust-vmm/kvm-ioctls/issues/59 so that we can release `kvm-ioctls v0.4.0`", "updated_at": "2019-11-25T11:51:36Z", "url": "https://api.github.com/repos/rust-vmm/kvm-ioctls/issues/comments/558121682", "author_association": "MEMBER", "html_url": "https://github.com/rust-vmm/kvm-ioctls/pull/71#issuecomment-558121682", "created_at": "2019-11-25T11:51:36Z", "id": 558121682, "node_id": "MDEyOklzc3VlQ29tbWVudDU1ODEyMTY4Mg=="}, {"user": {"following_url": "https://api.github.com/users/acatangiu/following{/other_user}", "url": "https://api.github.com/users/acatangiu", "site_admin": false, "gists_url": "https://api.github.com/users/acatangiu/gists{/gist_id}", "node_id": "MDQ6VXNlcjMxOTE3OTcz", "starred_url": "https://api.github.com/users/acatangiu/starred{/owner}{/repo}", "gravatar_id": "", "id": 31917973, "events_url": "https://api.github.com/users/acatangiu/events{/privacy}", "avatar_url": "https://avatars3.githubusercontent.com/u/31917973?v=4", "login": "acatangiu", "repos_url": "https://api.github.com/users/acatangiu/repos", "subscriptions_url": "https://api.github.com/users/acatangiu/subscriptions", "followers_url": "https://api.github.com/users/acatangiu/followers", "html_url": "https://github.com/acatangiu", "received_events_url": "https://api.github.com/users/acatangiu/received_events", "type": "User", "organizations_url": "https://api.github.com/users/acatangiu/orgs"}, "issue_url": "https://api.github.com/repos/rust-vmm/kvm-ioctls/issues/71", "body": "Changed `kvm_ioctls::Result` to work with `errno::Result` instead of `io::Result`.\r\n    \r\nNo longer exporting `kvm_ioctls::Result`. Users of this crate should not have to use `kvm_ioctls::Result` outside the crate.\r\n    \r\nNow exporting `kvm_ioctls::Error` type definition so that users of this crate can create their own wrapping errors without having to know the `Error` type used internally by this crate.\r\n\r\n```rust\r\nenum UserError {\r\n  FailedSomeOperation(kvm_ioctls::Error),\r\n}\r\n```\r\nNo need to assume `io::Error` or `errno::Error` used internally by `kvm_ioctls`.\r\n\r\n@andreeaflorescu @jiangliu what do you think?", "updated_at": "2019-11-25T16:32:24Z", "url": "https://api.github.com/repos/rust-vmm/kvm-ioctls/issues/comments/558234602", "author_association": "MEMBER", "html_url": "https://github.com/rust-vmm/kvm-ioctls/pull/71#issuecomment-558234602", "created_at": "2019-11-25T16:32:24Z", "id": 558234602, "node_id": "MDEyOklzc3VlQ29tbWVudDU1ODIzNDYwMg=="}]